version: '3'
services:
  integrationtests:
    build:
      context: .
      dockerfile: local.Dockerfile
    command: npm run test:integration
    volumes:
      - ./tests-integration:/app/tests-integration
      - ./tests:/app/tests
      - ./src:/app/src
    ports:
      - 3000:3000
    depends_on:
      - localstack
    environment:
      LOGLEVEL: debug
      DYNAMO_TABLENAME: test
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
